### PR TITLE
Generalize original code

### PR DESCRIPTION
**Pull request by bsantan**

### CODE REVIEW

**Review by lagillenwater — APPROVED** [review]
Looks good.

**Review by Nourah-Salem — APPROVED** [review]

**Comment by Nourah-Salem** [comment]
Approved!

**Comment by lagillenwater** [comment]
In create_graph.py, line 20 reorganizes edgelist into [['Subject', 'Object', 'Predicate']].  Downloaded file has lower case column names (i.e. instance_relationsOnly_OWLNETS/PheKnowLator_v3.0.2_full_instance_relationsOnly_OWLNETS_Triples_Identifiers.txt),

**Comment by bsantan** [comment]
I updated create_graph so that the column names are always lower case to avoid this, because the edgelist I was using had them as upper case

**Pull request merged**
